sonar.projectKey=jovialio_obsidian-mdx
sonar.organization=jovialio
sonar.projectName=obsidian-mdx

sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**,main.js,main.css

sonar.typescript.tsconfigPath=tsconfig.json
